### ISSUE TITLE
Broken in 2.4?

### ISSUE THREAD

**Issue by Synchro** [fubarhouse/fubarhouse.npm#46]
I'm trying to install on Ubuntu 16.04 using ansible 2.4.0, but it fails to install nvm (though it doesn't notice), and then other steps fail as a consequence. This is my playbook:

```yaml
---
- hosts: adminservers
  become: yes
  roles:
    - fubarhouse.nodejs
  vars:
    node_version: 6.3.1
    node_versions:
      - 6.3.1
    install_iojs: false
    install_ivm: false
  tasks:
    - name: Install PM2
      npm:
        name: pm2
        global: yes
```

Everything seems to work up to the point where it tries to run nvm, which fails as it's not there (also note the deprecation notices for ansible 2.4):

```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.

PLAY [adminservers] **************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************************************
ok: [host.example.com]

TASK [fubarhouse.nodejs : NodeJS | Install dependencies (CentOS)] ****************************************************************************************************************************************************************************************************
skipping: [host.example.com] => (item=[]) 

TASK [fubarhouse.nodejs : NodeJS | Install dependencies (Debian)] ****************************************************************************************************************************************************************************************************
ok: [host.example.com] => (item=[u'curl', u'gcc', u'git', u'findutils', u'make', u'rsync', u'tar'])

TASK [fubarhouse.nodejs : NodeJS | Install dependencies (RedHat)] ****************************************************************************************************************************************************************************************************
skipping: [host.example.com] => (item=[]) 

TASK [fubarhouse.nodejs : Define user variable for ssh use] **********************************************************************************************************************************************************************************************************
ok: [host.example.com]

TASK [fubarhouse.nodejs : Define user variable for non-ssh use] ******************************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : Get $HOME] *********************************************************************************************************************************************************************************************************************************
ok: [host.example.com]

TASK [fubarhouse.nodejs : Set $HOME] *********************************************************************************************************************************************************************************************************************************
ok: [host.example.com]

TASK [fubarhouse.nodejs : Set default ivm installation directory] ****************************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : Set default nvm installation directory] ****************************************************************************************************************************************************************************************************
ok: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Looking at shell profiles] ***********************************************************************************************************************************************************************************************************
ok: [host.example.com] => (item=.bash_profile)

TASK [fubarhouse.nodejs : NVM | Clean-up] ****************************************************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Clean-up default version from shell profiles] ****************************************************************************************************************************************************************************************
skipping: [host.example.com] => (item={'_ansible_parsed': True, u'stat': {u'exists': False}, '_ansible_item_result': True, '_ansible_no_log': False, 'failed': False, u'changed': False, 'item': u'.bash_profile', u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'.bash_profile', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}}) 

TASK [fubarhouse.nodejs : NVM | Clean-up other versions from shell profiles] *****************************************************************************************************************************************************************************************
skipping: [host.example.com] => (item=[{'_ansible_parsed': True, u'stat': {u'exists': False}, u'changed': False, '_ansible_no_log': False, 'item': u'.bash_profile', '_ansible_item_result': True, 'failed': False, u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'.bash_profile', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}}, u'6.3.1']) 

TASK [fubarhouse.nodejs : NodeJS | Remove imported exports not associated to specific versions] **********************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Check] *******************************************************************************************************************************************************************************************************************************
ok: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Ensure permissions are set] **********************************************************************************************************************************************************************************************************
ok: [host.example.com] => (item={u'path': u'/usr/local/lib/node_modules'})
ok: [host.example.com] => (item={u'path': u'/Users/ubuntu/.npm'})
ok: [host.example.com] => (item={u'path': u'/Users/ubuntu/.nvm'})

TASK [fubarhouse.nodejs : NVM | Get distribution] ********************************************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Create temporary extraction directory] ***********************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Create pernament extraction directory] ***********************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Unpack distribution] *****************************************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Moving to installation directory] ****************************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Moving to installation directory] ****************************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Remove temporary data] ***************************************************************************************************************************************************************************************************************
skipping: [host.example.com] => (item=/tmp/6.3.tar.gz) 
skipping: [host.example.com] => (item=/tmp/nvm-6.3) 

TASK [fubarhouse.nodejs : NVM | Clone] *******************************************************************************************************************************************************************************************************************************
ok: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Install] *****************************************************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Ensure permissions are set] **********************************************************************************************************************************************************************************************************
ok: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Create an executable] ****************************************************************************************************************************************************************************************************************
skipping: [host.example.com]

TASK [fubarhouse.nodejs : NVM | Get versions] ************************************************************************************************************************************************************************************************************************
fatal: [host.example.com]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/nvm ls-remote", "delta": "0:00:00.008074", "end": "2017-09-27 14:18:44.646110", "failed": true, "msg": "non-zero return code", "rc": 127, "start": "2017-09-27 14:18:44.638036", "stderr": "/bin/bash: /usr/local/bin/nvm: No such file or directory", "stderr_lines": ["/bin/bash: /usr/local/bin/nvm: No such file or directory"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/Users/marcus/ansible-config-scripts/nodejs.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************
host.example.com : ok=11   changed=0    unreachable=0    failed=1   
```

**Comment by fubarhouse** [comment]
Thanks for raising this.

I'm yet to run the tests against Ansible 2.4, but I'll prioritise it :)

**Comment by fubarhouse** [comment]
So tests in Ansible 2.4 are passing fine - as I expected.

Looking further into the causes of your play I can identify the following facts
* The nvm installation directory was found to exist
* The installation of the executable script (default /usr/local/bin/nvm) skipped due to the above.
* The execution of the executable script failed due to not existing.

I've committed two changes, one which is a direct response to this which removes the logic preventing the executable script from installing only in certain conditions - the other is part of something identified using roles over remote hosts (found in my golang role) - which will be rolled out on all of my roles if I can ever get to them all.

I'm about to start releasing v1.8.1, I would be appreciative if you could inform me if this problem is fixed, or another problem stems from this. The release will be out on the galaxy within the next couple of hours (at most).

**Comment by fubarhouse** [comment]
Release v1.8.1 is now available via Ansible Galaxy.

Again, I'd appreciate the feedback about weather or not this fixes it.

Release notes can be found in #47, but not on github tag notes (yet).

**Comment by Synchro** [comment]
I'm still having trouble with this. I spotted that it appears to be using some wrong paths - I'm running ansible on macOS, but the targets are Linux, and this role is creating files in macOS-style `/Users/ubuntu/.nvm` rather than linuxish `/home/ubuntu/.nvm`, for example:

```
TASK [fubarhouse.nodejs : NVM | Ensure permissions are set] **********************************************************************************************************************************************************************************************************
ok: [webadmin2.example.com] => (item={u'path': u'/usr/local/lib/node_modules'}) => {"changed": false, "failed": false, "gid": 0, "group": "root", "item": {"path": "/usr/local/lib/node_modules"}, "mode": "0777", "owner": "ubuntu", "path": "/usr/local/lib/node_modules", "size": 4096, "state": "directory", "uid": 1000}
ok: [webadmin2.example.com] => (item={u'path': u'/Users/ubuntu/.npm'}) => {"changed": false, "failed": false, "gid": 0, "group": "root", "item": {"path": "/Users/ubuntu/.npm"}, "mode": "0777", "owner": "ubuntu", "path": "/Users/ubuntu/.npm", "size": 4096, "state": "directory", "uid": 1000}
ok: [webadmin2.example.com] => (item={u'path': u'/Users/ubuntu/.nvm'}) => {"changed": false, "failed": false, "gid": 0, "group": "root", "item": {"path": "/Users/ubuntu/.nvm"}, "mode": "0777", "owner": "ubuntu", "path": "/Users/ubuntu/.nvm", "size": 4096, "state": "directory", "uid": 1000}
```

I suspect that could lead to quite a few other issues.

I'm also getting lots of warnings like this:

```
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: "{{ item }}" in nodejs_available_versions.stdout and item not in installed_nodejs_versions.stdout
```

**Comment by fubarhouse** [comment]
@Synchro, That's an interesting find!

You may want to notice that in defaults/main.yml, those paths are being set - but I will do something about this pro-actively.

```
nodejs_folder_paths:
  - path: "/usr/local/lib/node_modules"
  - path: "/Users/{{ fubarhouse_user }}/.npm"
  - path: "/Users/{{ fubarhouse_user }}/.nvm"
```

I'll get the notices done too - I recently fixed the same problem on another role.

Is the remainder of this role working as expected for you?

**Comment by Synchro** [comment]
No, it still fails like this:

```
TASK [fubarhouse.nodejs : Define user variable for ssh use] **********************************************************************************************************************************************************************************************************
ok: [webadmin2.example.com] => {"ansible_facts": {"fubarhouse_user": "ubuntu"}, "changed": false, "failed": false}

TASK [fubarhouse.nodejs : Define user variable for non-ssh use] ******************************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : Get $HOME] *********************************************************************************************************************************************************************************************************************************
ok: [webadmin2.example.com] => {"changed": false, "cmd": "echo $HOME", "delta": "0:00:00.011348", "end": "2017-09-29 12:54:17.801769", "failed": false, "rc": 0, "start": "2017-09-29 12:54:17.790421", "stderr": "", "stderr_lines": [], "stdout": "/root", "stdout_lines": ["/root"]}

TASK [fubarhouse.nodejs : Set $HOME] *********************************************************************************************************************************************************************************************************************************
ok: [webadmin2.example.com] => {"ansible_facts": {"fubarhouse_user_dir": "/root"}, "changed": false, "failed": false}

TASK [fubarhouse.nodejs : Set default ivm installation directory] ****************************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : Set default nvm installation directory] ****************************************************************************************************************************************************************************************************
ok: [webadmin2.example.com] => {"ansible_facts": {"nvm_install_dir": "/root/.nvm"}, "changed": false, "failed": false}

TASK [fubarhouse.nodejs : NVM | Looking at shell profiles] ***********************************************************************************************************************************************************************************************************
ok: [webadmin2.example.com] => (item=.bash_profile) => {"changed": false, "failed": false, "item": ".bash_profile", "stat": {"exists": false}}

TASK [fubarhouse.nodejs : NVM | Clean-up] ****************************************************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NVM | Clean-up default version from shell profiles] ****************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => (item={'_ansible_parsed': True, u'stat': {u'exists': False}, '_ansible_item_result': True, '_ansible_no_log': False, 'failed': False, u'changed': False, 'item': u'.bash_profile', u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'.bash_profile', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}})  => {"changed": false, "item": {"changed": false, "failed": false, "invocation": {"module_args": {"checksum_algorithm": "sha1", "follow": false, "get_attributes": true, "get_checksum": true, "get_md5": true, "get_mime": true, "path": ".bash_profile"}}, "item": ".bash_profile", "stat": {"exists": false}}, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NVM | Clean-up other versions from shell profiles] *****************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => (item=[{'_ansible_parsed': True, u'stat': {u'exists': False}, u'changed': False, '_ansible_no_log': False, 'item': u'.bash_profile', '_ansible_item_result': True, 'failed': False, u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'.bash_profile', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}}, u'6.3.1'])  => {"changed": false, "item": [{"_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": true, "changed": false, "failed": false, "invocation": {"module_args": {"checksum_algorithm": "sha1", "follow": false, "get_attributes": true, "get_checksum": true, "get_md5": true, "get_mime": true, "path": ".bash_profile"}}, "item": ".bash_profile", "stat": {"exists": false}}, "6.3.1"], "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NodeJS | Remove imported exports not associated to specific versions] **********************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NVM | Check] *******************************************************************************************************************************************************************************************************************************
ok: [webadmin2.example.com] => {"changed": false, "failed": false, "stat": {"exists": false}}

TASK [fubarhouse.nodejs : NVM | Ensure permissions are set] **********************************************************************************************************************************************************************************************************
ok: [webadmin2.example.com] => (item={u'path': u'/usr/local/lib/node_modules'}) => {"changed": false, "failed": false, "gid": 0, "group": "root", "item": {"path": "/usr/local/lib/node_modules"}, "mode": "0777", "owner": "ubuntu", "path": "/usr/local/lib/node_modules", "size": 4096, "state": "directory", "uid": 1000}
ok: [webadmin2.example.com] => (item={u'path': u'/Users/ubuntu/.npm'}) => {"changed": false, "failed": false, "gid": 0, "group": "root", "item": {"path": "/Users/ubuntu/.npm"}, "mode": "0777", "owner": "ubuntu", "path": "/Users/ubuntu/.npm", "size": 4096, "state": "directory", "uid": 1000}
ok: [webadmin2.example.com] => (item={u'path': u'/Users/ubuntu/.nvm'}) => {"changed": false, "failed": false, "gid": 0, "group": "root", "item": {"path": "/Users/ubuntu/.nvm"}, "mode": "0777", "owner": "ubuntu", "path": "/Users/ubuntu/.nvm", "size": 4096, "state": "directory", "uid": 1000}

TASK [fubarhouse.nodejs : NVM | Get distribution] ********************************************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NVM | Create temporary extraction directory] ***********************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NVM | Create pernament extraction directory] ***********************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NVM | Unpack distribution] *****************************************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NVM | Moving to installation directory] ****************************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NVM | Moving to installation directory] ****************************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NVM | Remove temporary data] ***************************************************************************************************************************************************************************************************************
skipping: [webadmin2.example.com] => (item=/tmp/6.3.tar.gz)  => {"changed": false, "item": "/tmp/6.3.tar.gz", "skip_reason": "Conditional result was False", "skipped": true}
skipping: [webadmin2.example.com] => (item=/tmp/nvm-6.3)  => {"changed": false, "item": "/tmp/nvm-6.3", "skip_reason": "Conditional result was False", "skipped": true}

TASK [fubarhouse.nodejs : NVM | Clone] *******************************************************************************************************************************************************************************************************************************
fatal: [webadmin2.example.com]: FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --force 6.3", "failed": true, "msg": "Failed to checkout 6.3", "rc": 1, "stderr": "error: pathspec '6.3' did not match any file(s) known to git.\n", "stderr_lines": ["error: pathspec '6.3' did not match any file(s) known to git."], "stdout": "", "stdout_lines": []}
```

I think there is confusion in the paths - it seems to be using both `Users/ubuntu/.nvm` and `/root/.nvm`, resulting in it missing folders where it expects them. This is what I meant by it leading to other issues.

**Comment by fubarhouse** [comment]
Another set of changes are coming.

From there I can identify the nvm_version is set to "6.3" instead of the default "v0.33.2" - which will never work... After the next set of changes have finished, could you please set the following variable:

`nvm_version: v0.33.2`

I'll let you know once the current changes are done.

**Comment by fubarhouse** [comment]
Could you please test against branch dev-1.8.x with the above variable?

If not, I'll release tomorrow with the following changes:
* Remove deprecated jinja2 syntax
* Fixes paths to node folders to support dynamic OS selection.

I'm inclined to do something about that variable acting up... If it continues I'll replace it to a fixed version.

**Comment by Synchro** [comment]
How do I get galaxy to load a dev version? Or do I drop a copy of the dev version into my roles folder instead?

**Comment by fubarhouse** [comment]
You'll need to clone the repository to a specific folder/location.

I suspect you'll be able to do the following, but you should check the paths before doing so:
```
rm -rf /etc/ansible/roles/fubarhouse.nodejs && git clone -b dev-1.8.x https://github.com/fubarhouse/ansible-role-nodejs.git /etc/ansible/roles/fubarhouse.nodejs
```

You can double-check it's the right location by using:
```
ls -lah /etc/ansible/roles/
```

**Comment by fubarhouse** [comment]
I'm beginning the release process for the two identified problems with v1.8.1 as described above.

They aren't exactly impacting you directly but they have been fixed.

After this one is done, update and set the following variable:
```
nvm_version: v0.33.2
```

From there, let me know if anything else comes up. The above variable *should* be set as described in the defaults/main.yml - I do not know why that wouldn't be set incorrectly - it's supposed to match up with tags on the nvm repository.

**Update**:
1.8.2 is now released to the galaxy.

I understand we haven't concluded here, but I want you to know your input is invaluable to me. A pair of eyes which aren't my own can always find some really useful things to make a project better - thanks :)

**Comment by Synchro** [comment]
It works! Clearly it's much happier now! Just two warnings:

At the start (this could be generic?):

```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
```

and this one towards the end:

```
TASK [fubarhouse.nodejs : NodeJS | Verify version in use] ************************************************************************************************************************************************************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: node_current_version.stdout.find("{{ node_version }}") == -1
```

but overall it's now working for me, thank you very much.

**Comment by fubarhouse** [comment]
## Warning 1

The first warning should be disabled.

Early 2019, when Ansible 2.8 is released the module controlling this will be completely removed. Having said that, the new modules were only introduced in 2.4 and by making those changes it will break on potentially a large portion of users, and I do not maintain the docker images for CentOS, Ubuntu 12.04, 14.04, 16.04 or Debian7 - I don't even know if the changes are compatible with those images.

Making these specific changes now would be premature and dangerous, therefore it is my intention (and not my preference) to begin making these changes after the release of Ansible 2.6 after May 2018, and these changes would require any systems using pre-Ansible 2.4 to upgrade to Ansible 2.4 or later.

* http://docs.ansible.com/ansible/latest/intro_configuration.html#deprecation-warnings
* An example of this file can be found here: https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg
* In the above example, search for the deprecation warnings and uncomment the relevant lines, and note the following at the top of the example config file:
```
# nearly all parameters can be overridden in ansible-playbook
# or with command line flags. ansible will read ANSIBLE_CONFIG,
# ansible.cfg in the current working directory, .ansible.cfg in
# the home directory or /etc/ansible/ansible.cfg, whichever it
# finds first
```
**Know that I'm very well aware of this, and it affects every single ansible role I manage...**

## Warning 2

* Commit 0c9b081f96469e0e7a63e3a489f418aa51c963f6 has been pushed.
* Travis tests are now being executed.

**Comment by fubarhouse** [comment]
@Synchro this should finally be closable, could you please confirm or provide feedback?

**Comment by Synchro** [comment]
I just ran into this again, so I updated and re-ran, and it does indeed appear to be solved. Some other issues in 2.7 now though...

**Comment by fubarhouse** [comment]
I'm working with quite a bit of change in the branch `version-2` at the moment...

I'll try to prioritize this.
